apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
        - name: go-microservice
          image: your-dockerhub-user/go-microservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GREETING_PREFIX
              value: "Hi"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-microservice
spec:
  type: LoadBalancer
  selector:
    app: go-microservice
  ports:
    - port: 80
      targetPort: 8080